# -*- coding: utf-8 -*-
"""Countdown timer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EEa0txJGHQ-5Wcn6sgpKJh0UCrmMeR4Z
"""

import time

print("==== Countdown Timer ====")

seconds = int(input("Enter time in seconds: "))

for i in range(seconds, 0, -1):
    print(f" Time Left: {i} seconds", end="\r")
    time.sleep(1)

print("\n Time's up!")

